# Date: 2024-8-26
# Author: Generated by GoCodeo.


import unittest 

from board.admin import UserAdmin 

from dj.models import User 

class TestUserAdmin(unittest.TestCase):

	    def test_non_existent_username(self):
	        # Create a user with a non-existent username
	        user = User(username='nonexistent', email='nonexistent@example.com')
	        user.save()
	
	        # Create an instance of UserAdmin
	        user_admin = UserAdmin(User, admin.site)
	
	        # Get the list of users displayed in the list view
	        users = user_admin.get_queryset(None)
	
	        # Check if the user with non-existent username is not in the list
	        self.assertNotIn(user, users) 


