# Date: 2024-8-26
# Author: Generated by GoCodeo.


import unittest 

from board.admin import UserAdmin 

from dj.models import User 

class TestUserAdmin(unittest.TestCase):

	    def test_list_display(self):
	        admin = UserAdmin(User, None)
	        self.assertEqual(admin.list_display, ('username', 'email', 'date_joined')) 


