# Date: 2024-8-26
# Author: Generated by GoCodeo.


import unittest 

from board.admin import UserAdmin 

from dj.models import User 

class TestUserAdmin(unittest.TestCase):

	    def test_non_existent_email(self):
	        # Create a non-existent email
	        email = 'nonexistent@example.com'
	        # Create a UserAdmin instance
	        user_admin = UserAdmin(User, admin.site)
	        # Call the get_search_results method with the non-existent email
	        search_results = user_admin.get_search_results(request=None, queryset=User.objects.all(), search_term=email)
	        # Assert that the search results are empty
	        self.assertEqual(len(search_results), 0) 


