# Date: 2024-8-26
# Author: Generated by GoCodeo.


import unittest 

from board.admin import UserAdmin 

from dj.models import User 

class TestUserAdmin(unittest.TestCase):

	    def test_search_functionality(self):
	        # Create some test users
	        User.objects.create(username='user1', email='user1@example.com')
	        User.objects.create(username='user2', email='user2@example.com')
	        User.objects.create(username='user3', email='user3@example.com')
	        # Search for a user by username
	        result1 = UserAdmin.search_fields[0].search('user1')
	        self.assertEqual(result1.count(), 1)
	        self.assertEqual(result1[0].username, 'user1')
	        # Search for a user by email
	        result2 = UserAdmin.search_fields[1].search('user2@example.com')
	        self.assertEqual(result2.count(), 1)
	        self.assertEqual(result2[0].email, 'user2@example.com') 


