# Date: 2024-8-26
# Author: Generated by GoCodeo.


import unittest 

from board.admin import UserAdmin 

from dj.models import User 

class TestUserAdmin(unittest.TestCase):

	    def test_filter_date_joined(self):
	        # Create some test users
	        user1 = User.objects.create(username='user1', email='user1@example.com', date_joined='2021-01-01')
	        user2 = User.objects.create(username='user2', email='user2@example.com', date_joined='2021-02-01')
	        user3 = User.objects.create(username='user3', email='user3@example.com', date_joined='2021-03-01')
	        # Filter users by date joined
	        filtered_users = UserAdmin.list_filter[0].queryset(None, User.objects.all(), None)
	        # Check if the filtered users match the expected result
	        self.assertEqual(list(filtered_users), [user1, user2, user3]) 


