# Date: 2024-8-26
# Author: Generated by GoCodeo.


import unittest 

from board.admin import UserAdmin 

from dj.models import User 

class TestUserAdmin(unittest.TestCase):

	    def test_empty_date_joined(self):
	        user = User(username='testuser', email='test@example.com', date_joined='')
	        self.assertEqual(user.date_joined, '') 


