# Date: 2024-8-26
# Author: Generated by GoCodeo.


import unittest 

from board.admin import UserAdmin 

from dj.models import User 

class TestUserAdmin(unittest.TestCase):

	    def test_user_admin_list_view(self):
	        admin_site = admin.AdminSite()
	        user_admin = UserAdmin(User, admin_site)
	        expected_fields = ['username', 'email', 'date_joined']
	        self.assertEqual(user_admin.list_display, expected_fields)
	 


