# Generated by Django 5.1 on 2024-09-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_user_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
    ]
