# Generated by Django 5.1 on 2024-09-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
