# Generated by Django 5.1 on 2024-09-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0005_user_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_trusted_user",
            field=models.BooleanField(default=False),
        ),
    ]
