# Generated by Django 5.1 on 2024-09-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0007_familytodoitem_habit_samstodoitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_trusted_user",
        ),
        migrations.AddField(
            model_name="habit",
            name="current_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="daily",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="target_count",
            field=models.IntegerField(default=1),
        ),
    ]
