# Generated by Django 5.1 on 2024-09-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0008_remove_post_is_trusted_user_habit_current_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_trusted_user",
            field=models.BooleanField(default=False),
        ),
    ]
