# Generated by Django 5.1 on 2024-09-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0009_userprofile_is_trusted_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
