# Generated by Django 5.1 on 2024-09-28 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0010_alter_user_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familytodoitem",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="family_todos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
